require 'rubygems'
require 'nerderyiOSbuild'

NerderyiOSBuild::Tasks.new do |config|
        # Xcode project info
        config.target = "<Target name to use>"
        config.app_name = "<Name of *.app build product generated by your app, without the .app extension>"
        
        # Xcode workspace information. Uncomment and customize for project using CocoaPods.
        #config.workspace_path = "<Your workspace name>.xcworkspace"
        #config.scheme = "<Scheme name to use>"
        #config.build_dir = "build/<Target name>/Build/Products"

        # Xcode configuration profile to build
        config.configuration = "Enterprise-Debug"
end